# Snakemake config
args:
    reads:
    assembly:
    library:
    bams:
    histograms:
    max_depth:
    output: 'koverage.out/'
    log: 'koverage/koverage.log'
resources:
    map:
        cpu: 4
        mem_mb: 16000
        time_min: 120
    pipe:
        cpu: 1
        mem_mb: 2000
        time_min: 1
