# Snakemake config
args:
    reads:
    assembly:
    library:
    bams:
    bin_width:
    kmer_size:
    kmer_sample:
    kmer_min:
    kmer_max:
    output: 'koverage.out/'
    log: 'koverage/koverage.log'
params:
    jellyfish: "-s 1G -c 2 --out-counter-len=2 -L 2"
resources:
    map:
        cpu: 8
        mem_mb: 16000
        time_min: 120
