resources:
    med:
        cpu: 8
        mem: 16000
        time: 120
    ram:
        cpu: 2
        mem: 8000
        time: 480
koverage:
    params:
        jellyfish:
            -C 
            -s 1G 
            -c 2 
            --out-counter-len=2 
            -L 2
        coverm:
            -m count
            -m rpkm
            -m tpm
            -m mean
            -m covered_bases
            -m variance