# Snakemake config
args:
    reads:
    assembly:
    library:
    bams:
    maxDepth:
    output: 'koverage.out/'
    log: 'koverage/koverage.log'
resources:
    map:
        threads: 8
        mem_mb: 16000
        time_min: 120
    bam:
        threads: 4
        mem_mb: 8000
        time_min: 120
