modules:
    paired:
        preflight:
            "rules/samples_pe.smk"
        mapping:
            "rules/map_pe.smk"
    single:
        preflight:
            "rules/samples_se.smk"
        mapping:
            "rules/map_se.smk"
    longread:
        preflight:
            "rules/samples_se.smk"
        mapping:
            "rules/map_lr.smk"
